apiVersion: v1
kind: Namespace
metadata:
  name: test ##################
---
apiVersion: v1 
kind: Pod
metadata:
  name: myapp-python
  namespace: test  ##################
  labels:
    run: myapp-python-pod-labeled 
spec:
  containers:
  - image: nginx  
    name: nginx-container
    resources:
        limits:
          memory: "1024Mi"
          cpu: "200m"
    ports:
    - containerPort: 9090

    #Warning  FailedScheduling  18s (x3 over 80s)  default-scheduler  0/3 nodes are available: 1 Insufficient cpu, 3 Insufficient memory.
    