apiVersion: v1
kind: Namespace
metadata:
  name: web 
kind: Pod
metadata:
  name: myapp-redis 
  labels:
    run: myapp-redis-pod-labeled 
spec:
  containers:
  - image: redis 
    name: redis-container
    ports:
    - containerPort: 9090