apiVersion: v1
kind: Namespace
metadata:
  name: web 
---
apiVersion: v1 
kind: Pod
metadata:
  name: myapp-redis
  namespace: web  
  labels:
    run: myapp-redis-pod-labeled 
spec:
  containers:
  - image: redis 
    name: redis-container
    ports:
    - containerPort: 9090