apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    run: myapp-pod-labeled 
spec:
  containers:
  - image: nginx
    name: nginx-container
    ports:
    - containerPort: 80
  - image: redis
    name: redis-container
    ports:
    - containerPort: 8080
  - image: memcached
    name: memcached-container
    ports:
    - containerPort: 9090
  - image: consul
    name: consul-container 
    ports:
    - containerPort: 9191

    